projekt_szkoleniowy/Controllers/AutEditController.cs
using System.Linq;
using System.Web.Mvc;
using projekt_szkoleniowy.Models;

namespace projekt_szkoleniowy.Controllers
{
    public class AutEditController : Controller
    {
        DB db = new DB();

        public ActionResult Index()
        {
            /*Check if database has elements*/
            if (db.tAuthors.Count() > 0)
            {
                var AutList = (from item in db.tAuthors
                               orderby item.Surname
                               select item).ToList();
                return View(AutList);
            }
            else
            {
                return View();
            }
        }

        [HttpGet]

        public ActionResult AutEdit(int? id)
        {
            Author toEdit;
            /*Check if author exist*/
            if (id != null)
            {
                toEdit = db.tAuthors.Find(id);
                if (toEdit == null)
                {
                    return new HttpNotFoundResult();
                }
            }
            else
            {
                toEdit = new Author();
            }
            return View(toEdit);
        }

        [HttpGet]

        public ActionResult AutDel(int id)
        {
            Author toDel;
            toDel = db.tAuthors.Find(id);
            if (toDel == null)
            {
                return new HttpNotFoundResult();
            }
            return View(toDel);
        }

        [HttpPost]

        public ActionResult AutEdit(Author author)
        {
            if (ModelState.IsValid)
            {
                Author toEdit;
                /*Check if author is new or edited*/
                if (author.Id == 0)
                {
                    toEdit = new Author();
                    db.tAuthors.Add(author);
                    db.SaveChanges();
                }
                else
                {
                    toEdit = db.tAuthors.Find(author.Id);
                    if (toEdit != null)
                    {
                        toEdit.Name = author.Name;
                        toEdit.Surname = author.Surname;
                    }
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(author);
        }

        [HttpPost]

        public ActionResult AutDel(Author author)
        {
            Author toDel;
            toDel = db.tAuthors.Find(author.Id);
            if (toDel != null)
            {
                db.tAuthors.Remove(toDel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

projekt_szkoleniowy/Controllers/AutListController.cs
using System.Linq;
using System.Web.Mvc;
using projekt_szkoleniowy.Models;

namespace projekt_szkoleniowy.Controllers
{
    public class AutListController : Controller
    {
        public ActionResult Index()
        {
            DB db = new DB();
            /*Check if database has elements*/
            if (db.tAuthors.Count() > 0)
            {
                var AutList = (from item in db.tAuthors
                               orderby item.Name
                               select item).ToList();
                return View(AutList);
            }
            else
            {
                return View();
            }
        }
    }
}

projekt_szkoleniowy/Controllers/BookEditController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using projekt_szkoleniowy.Models;

namespace projekt_szkoleniowy.Controllers
{
    public class BookEditController : Controller
    {
        DB db = new DB();

        public ActionResult Index()
        {
            /*Check if database has elements*/
            if (db.tBooks.Count() > 0)
            {
                var BookList = (from item in db.tBooks
                                orderby item.Title
                                select item).ToList();
                return View(BookList);
            }
            else
            {
                return View();
            }
        }

        [HttpGet]

        public ActionResult BookEdit(int? id)
        {
            Book toEdit;
            /*Check if book exist*/
            if (id != null)
            {
                toEdit = db.tBooks.Find(id);
                if (toEdit == null)
                {
                    return new HttpNotFoundResult();
                }
            }
            else
            {
                toEdit = new Book();
            }
            return View(toEdit);
        }

        [HttpGet]

        public ActionResult BookDel(int? id)
        {
            Book toDel;
            toDel = db.tBooks.Find(id);
            if (toDel == null)
            {
                return new HttpNotFoundResult();
            }
            return View(toDel);
        }

        [HttpPost]

        public ActionResult BookEdit(Book book)
        {
            if (ModelState.IsValid)
            {
                Book toEdit;
                /*Check if book is new or edited*/
                if (book.Id == 0)
                {
                    /*Search author name and surname through database*/
                    Author aut = db.tAuthors.Where(x => x.Name == book.Author.Name &&
                    x.Surname == book.Author.Surname).FirstOrDefault();

                    /*Check if author exist*/
                    if (aut != null)
                    {
                        book.Author = aut;
                        db.tBooks.Add(book);
                        db.SaveChanges();
                    }
                    else
                    {
                        db.tAuthors.Add(book.Author);
                        db.tBooks.Add(book);
                        db.SaveChanges();
                    }
                }
                /*Book is edited*/
                else
                {
                    toEdit = db.tBooks.Find(book.Id);
                    if (toEdit != null)
                    {
                        toEdit.Title = book.Title;
                        toEdit.ReleaseDate = book.ReleaseDate;
                        toEdit.ISBN = book.ISBN;
                        toEdit.Author = new Author();

                        Author aut = db.tAuthors.Where(x => x.Name == book.Author.Name &&
                            x.Surname == book.Author.Surname).FirstOrDefault();

                        toEdit.Author = aut;
                    }
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(book);
        }

        [HttpPost]

        public ActionResult BookDel(Book book)
        {
            Book toDel;
            toDel = db.tBooks.Find(book.Id);
            if (toDel != null)
            {
                db.tBooks.Remove(toDel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        /*Send list names and surnames for autocomplite*/
        public JsonResult GetAutNamesList(string term)
        {
            var autNameList = db.tAuthors.Where(x => x.Name.Contains(term)).Select(y => y.Name).ToList();

            return Json(autNameList, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetAutSurnamesList(string term)
        {
            var autSurnameList = db.tAuthors.Where(x => x.Surname.Contains(term)).Select(y => y.Surname).ToList();

            return Json(autSurnameList, JsonRequestBehavior.AllowGet);
        }
    }
}

projekt_szkoleniowy/Controllers/BookListController.cs
using System.Linq;
using System.Web.Mvc;
using projekt_szkoleniowy.Models;

namespace projekt_szkoleniowy.Controllers
{
    public class BookListController : Controller
    {
        public ActionResult Index()
        {
            DB db = new Models.DB();

            if (db.tBooks.Count() > 0)
            {
                var BookList = (from item in db.tBooks
                                orderby item.Title
                                select item).ToList();

                return View(BookList);
            }
            else
            {
                return View();
            }
        }
    }
}

projekt_szkoleniowy/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Biblioteka</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/custom.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <script>
        $(function () {
            $("#datepicker").datepicker({
                changeMonth: true,
                changeYear: true,
                dateFormat: "dd.mm.yy"
            });
        });
        var dateFormat = $(".selector").datepicker("option", "dateFormat");

        $(function () {
            $("#autNamesTags").autocomplete({
                source: '@Url.Action("GetAutNamesList")'
            });
        });

        $(function () {
            $("#autSurnamesTags").autocomplete({
                source: '@Url.Action("GetAutSurnamesList")'
            })
        })

    </script>
</head>

<body>
    <nav class="navbar navbar-fixed-top">
        <div class="navbar-header">
            <a class="nav navbar-nav">
                @Html.ActionLink("BIBLIOTEKA", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </a>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Listy <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("książek", "Index", "BookList")</li>
                        <li>@Html.ActionLink("autorów", "Index", "AutList")</li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Edycja <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("książek", "Index", "BookEdit")</li>
                        <li>@Html.ActionLink("autorów", "Index", "AutEdit")</li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Biblioteka</p>
        </footer>
    </div>

    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>